### ISSUE TITLE
The check on QGIS plugin version is too strict

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#479]
We are currently checking all the three version numbers, major, minor and maintenance: version 1.7.1 of the plugin is not working because we are looking for `COMPATIBILITY_VERSION = 1.7.0`.

We should check up to the second number (minor) only, since in any case no changes in the protocol should be expected without increasing the minor number.

```
COMPATIBILITY_VERSION = 1.7.0
1.6.x -> KO
1.7.0 -> OK
1.7.1 -> OK
...
1.7.x -> OK
```
We should also decide what to do if the minor number is greater, like 1.8.0 is this fine or not if the COMPATIBILITY_VERSION is 1.7.0 ? (I vote NO for the current status, but it should be YES)

**Comment by pslh** [comment]
The desired semantics of version numbers are as follows:

Changes to the patch version must be compatible both with previous and later versions:
If app can use 1.7.1, then it can use also 1.7.0 and 1.7.2.

I think that if a new format includes additional information (for new features) but does not break compatibility with the current applications, then the minor number should change, e.g. 1.8.0.
If app can use 1.7.1 then it can use 1.8.0 but not (necessarily) 1.6.1

If a new format is not compatibile with existing applications, then the major number should change.
If app can use 1.7.1 then it can not use 2.0.0

See also:
https://apr.apache.org/versioning.html#examples
