### ISSUE TITLE
IPT - Add zeros check for discrete vulnerability [risklib-related]

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-platform#491]
Add a check in the tool for:
"It is not valid to define a loss ratio = 0.0 with a corresponding coeff. of variation > 0.0" @bwyss

**Comment by micheles** [comment]
This should not be done by the platform. We discussed this with Ben and Paolo in the past, the validation must be done by oq-lite and the platform should just call a validation API. This is a project for the next sprint, though.

**Comment by CatalinaYepes** [comment]
I don't like the idea that the tool can generate files that can not be used directly in the engine for silly mistakes (plus, the check is very simple).

**Comment by daniviga** [comment]
That's true, but it will become very hard do maintain a validation (which is sometime very complex) in two different places; the platform is also not well covered by tests and hard to test, so I agree with @micheles

**Comment by micheles** [comment]
Me neither, this why they project of validating the files with oq-lite has been approved, in theory even for this sprint. In practice we could not do it in time. It would be a waste of Ben's time doing this in a sub-optimal way.

**Comment by nastasi-oq** [comment]
This bug is totally related to risklib, and will be fixed in the 'oq-engine' repository.
