### ISSUE TITLE
RIPT - Copy/paste does not work if columns are added

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#521]
In RIPT copy and paste does not work if any dropdown menu is changed and a column is added. It work when the page loads instead.

How to reproduce:
1 Load the RIPT app
2 Change the first dropdown available (Structural Costs) to any choice (like 'Aggregated')
3 Copy sample data from Excel o LibreOffice (like `a	b	c	d	e	f`)
4 Try to paste those values into the table. Nothing happens

It works is step 2 is skipped.
This is reproducible on the live Platform (v1.3.1 as writing) and has been reported by Desmond.

**Comment by nastasi-oq** [comment]
This problem not appears in d1669f9b5a82366884560e60cac3b051fcd826c9 (risk-ipt-new-vuln-tables branch, tag: ript-refact01)
