### ISSUE TITLE
RIPT - Chrome does not allow downloading the generated XML

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#522]
Chrome says:

![imgo](https://cloud.githubusercontent.com/assets/1818657/11816625/a638defc-a351-11e5-968d-eca142468dc1.jpg)

**Comment by CatalinaYepes** [comment]
Same problem for downloading the xml in Firefox and Safari

**Comment by nastasi-oq** [comment]
Fixed in 23f41bfe5da928f87bf778fc2e8d0109fb14468d (risk-ipt-new-vuln-tables branch).

**Comment by CatalinaYepes** [comment]
LGTM
