### ISSUE TITLE
RIPT - Exposure - Avoid empty <occupancies> tags

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-platform#538]
Currently, if the input exposure data does not include the number of occupants, i.e., if the **Day**, **Night**, and **Transit** checkboxes for **Occupants** in the input form are all left unchecked, the generated NRML still includes an empty occupancies tag for each asset:
```xml
<asset id="EUCENTRE-3" number="1" taxonomy="Concrete" >
	<location lon="9.1582" lat="45.18472"></location>
	<costs>
		<cost type="structural" value="6000000"></cost>
	</costs>
	<occupancies>
	</occupancies>
</asset>
```

This should be avoided.

**Comment by nastasi-oq** [comment]
Fixed on 'risk-ipt-new-vuln-tables', you can currently test it at:
http://oq-platform2-mn.gem.lan:8000/ript/ (from internal GEM lan)
