### ISSUE TITLE
Vulnerability - Bug for exporting functions in NRML format

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-platform#607]
When exporting functions in NRML format, some of them are exported with the full taxonomy, and some others with the short taxonomy.

See for example the output for the functions:

- https://platform.openquake.org/vulnerability/view/468/
- https://platform.openquake.org/vulnerability/view/469/

**Comment by nastasi-oq** [comment]
Now all curves are exported with the full taxonomy.

**Comment by CatalinaYepes** [comment]
All the curves should be exported in the short form of the taxonomy
