### ISSUE TITLE
Vulnerability - Some functions in the platform have the GEM taxonomy string wrong

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-platform#609]
The GEM taxonomy string specified in some curves is not correct, specially in the curves from HAZUS (these curves were added before implementing the validation).

See https://platform.openquake.org/vulnerability/view/469/

**Comment by nastasi-oq** [comment]
Each curve now has proper taxonomy on production and staging.
There are 2 issues not yet released:
  - gem/oq-platform-taxtweb#8 (committed and not released)
  - #611 (investigating)
