### ISSUE TITLE
Vulnerability - Update web link for Syner-G curves

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-platform#610]
For the fragility curves that have the `web link`
http://www.vce.at/SYNER-G/pdf/deliverables/D7.1_Deliverable_7.1_FINAL.pdf

update it for 
http://www.vce.at/SYNER-G/pdf/deliverables/D7.01_Deliverable_7.1_FINAL.pdf

**Comment by CatalinaYepes** [comment]
For all the fragility functions that have as Reference
`HAZUS-MH MR3 Technical Manual (FEMA, HAZUS, 2003) - Technical manual`

The name of the limit states should be updated:
`Slight, Moderate, Extensive, Complete` instead of `Slight, Moderate, Extensive, Collapse`

**Comment by nastasi-oq** [comment]
Done both (better split issues, please).
