### ISSUE TITLE
Use engine through its API

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#628]
We should stop importing engine and hazardlib stuff directly in the platform code and instead use the HTTP API.

The software stack used by our platform is getting too old and isn't compatible/tested with the engine anymore. We are facing the problem that platform and engine cannot be installed on the same env.

About the engine features used by the platform (xml validation) we already provide an HTTP API in 'openquake.server`: using this API we can install the in a separate venv with the right libraries and then make remote calls.

It's the same problem we had and we solved with QGIS.

**Comment by nastasi-oq** [comment]
Done.
