### ISSUE TITLE
urls.py is missing building-class

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#633]
Currently `urls.py` has `building-class` missing in both `master` and `1.7`. But we have it installed and running in production.

Deploying a new release breaks the application unless `urls.py` is manually updated.

```python
(r'^building-class/', include('openquakeplatform_building_class.urls', namespace='building_class')),
```

Blocked by https://github.com/gem/oq-platform/pull/627, blocks any new release.

**Comment by nastasi-oq** [comment]
``building-class`` django application now is included in installation procedure.
